build:
  version: "1.0"

accounts:
  message: "Welcome to SarathBank accounts related productio APIs "
  contactDetails:
    name: "Sarathkumar - Product Owner"
    email: "sarath@sarathbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384