build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Sarath - QA Lead"
    email: "sarath@sarathbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371